language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4

cache: yarn

install:
  - yarn add ci

before_script:
  - yarn lint
  - yarn compose:up

script:
  - yarn cypress:record --env host=$SITE --key $CYPRESS_KEY

after_script:
  - yarn compose:stop
